CREATE TABLE announcements (
    id INTEGER PRIMARY KEY,
    content TEXT NOT NULL CHECK(LENGTH(TRIM(content)) > 0),
    active BOOLEAN NOT NULL DEFAULT FALSE,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
